
import Head from 'next/head'
import styles from '../styles/HouseCarousel.module.css'
import Filter from "../comps/Filter"
import Link from "next/link"
import jsonData from "../data.json"

// pages/index.js
import Carousel from 'react-material-ui-carousel'
import { Paper } from '@mui/material'
import React from 'react'

export default function Home(props) {
 
  const srcs = props.jsonData.srcs;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Filter/>


        <div className={styles.carouselsContainer}>
          {srcs.map((src, index) => (
            <div className={styles.carouselContainer} key={index}>
          <Carousel key={src.id}
              autoPlay={false}
              navButtonsProps={{
                style: {
                  backgroundColor: '#458DB7',
                  padding: "3px"
                }
              }} 
              indicatorIconButtonProps={{
                style: {
                  color: '#999',
                  zIndex: 10,
                  marginBottom: "10px"
                                      }
                                    }}
                                    activeIndicatorIconButtonProps={{
                                      style: {
                                        color: '#458DB7',
                                        zIndex: 10 // 2
                                      }
                                  }}
                                  indicatorContainerProps={{
                                      style: {
                                          zIndex: 10,
                                          marginTop: "-20px",
                                      }
                                    }}
                                    >
            {src.images.map(img => <Item src={`/${img}`} height={30} width={30} id={src.id} key={src.id}/>)}
          </Carousel>
          </div>
))}

        
        </div>


      </main>

    </div>
  )
}

// Fetching data from the JSON file

export async function getStaticProps() {

  return {
    props: {
      jsonData: jsonData
    }
  }
}

function Item(props)
{

    return (
        <Link href={`/houses/${props.id}`}>
          <Paper className={styles.innerCarousel} style={{background: `url(${props.src}) center no-repeat`
                ,backgroundSize: "cover" ,height: "190px", borderRadius: "15px"}}>
          </Paper>
        </Link>
    )
}